color: null
fieldLayouts:
  e5d8461c-06f8-43f5-8fdb-551cce2eeccc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T08:36:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 86cd96d3-d3d5-4c6d-8b2d-a3b712e6aaac
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T08:38:35+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: subText
            includeInCards: false
            instructions: null
            label: SubText
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5435c5a0-d89f-44b1-b7bc-28b56e139724
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T08:38:35+00:00'
            elementCondition: null
            fieldUid: 35c35080-108d-485f-925f-407a5ab65a22 # Cover
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3235ce49-b660-4fdd-98d0-81de8bc022cc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: be4945cf-0e20-4f7d-ae8b-954afb896c15
        userCondition: null
handle: categories
hasTitleField: true
icon: ''
name: Categories
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
