color: null
fieldLayouts:
  4595d64a-fa80-43b7-bb69-1d88ba5642eb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T08:56:43+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 93cbbb3d-8ce5-43b8-8a10-ee93e20ea68b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T08:58:05+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: subText
            includeInCards: false
            instructions: null
            label: Subtext
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c40d569-4720-49ed-ad10-a564923f1a33
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d48bc62d-6d7b-46e9-b6fb-500217b9c77d
        userCondition: null
handle: locations
hasTitleField: true
icon: ''
name: Locations
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
