color: null
fieldLayouts:
  8c524d98-c436-4f16-800a-6037fb3855ec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T09:27:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 673277cf-dfd7-4153-b042-b5a806e9b60f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T09:30:59+00:00'
            elementCondition: null
            fieldUid: c07dd81f-5aba-43cb-94ad-04c2f6b4360e # Nav Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4458dd66-8f18-4e07-a8aa-8c7b4a14ad7d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ef2417de-77f0-4ae6-9902-47c63e6d034b
        userCondition: null
handle: navigationItems
hasTitleField: true
icon: ''
name: 'Navigation Items'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
