color: red
fieldLayouts:
  ea1b513d-80e1-43a7-a14b-dea41de95276:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T10:02:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fcca0a03-a18b-45a4-88f3-350df9dce251
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T10:04:32+00:00'
            elementCondition: null
            fieldUid: 35c35080-108d-485f-925f-407a5ab65a22 # Cover
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 164e5f67-7afa-4a3b-829c-54ff025935fa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T10:13:45+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: email
            includeInCards: false
            instructions: null
            label: Email
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e8760c9-5211-4272-a333-b5674bcba23f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T10:04:32+00:00'
            elementCondition: null
            fieldUid: 113d5bf0-c24d-41e4-ab4b-667cabd23c35 # City
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1da6c9b3-4388-4be7-88eb-85141a426016
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0525378a-aacc-4c30-bbd7-5c30faa52243
        userCondition: null
handle: realtors
hasTitleField: true
icon: person
name: Realtors
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
