color: purple
fieldLayouts:
  8b6c52b8-a43e-490a-8b2f-aa655f81664b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T10:20:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d941272a-01ee-4a1e-9f5d-805221ae65e0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T10:22:18+00:00'
            elementCondition: null
            fieldUid: 113d5bf0-c24d-41e4-ab4b-667cabd23c35 # City
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e676354-cf40-419d-9aaf-c6df2c8b7dd3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T10:22:18+00:00'
            elementCondition: null
            fieldUid: a3917b41-5b9e-455d-82b1-9867d010e228 # Body Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cf5cf4a-baab-48a6-b528-e4242fff9c4b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7e66cda7-46ec-4e10-8769-62887f40664a
        userCondition: null
handle: reviews
hasTitleField: true
icon: address-card
name: Reviews
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
