defaultPlacement: end
enableVersioning: true
entryTypes:
  - 72bd551d-db9d-4026-9ca2-c0038f5a5a50 # Locations
handle: locations
maxAuthors: 1
name: Locations
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f6eaef1f-2f88-4856-8eee-c5ae9620f572: # Craft Template
    enabledByDefault: true
    hasUrls: true
    template: locations/_entry.twig
    uriFormat: 'locations/{slug}'
structure:
  maxLevels: null
  uid: 2b3d5a21-0bc3-4331-b733-ef741c850638
type: structure
