defaultPlacement: end
enableVersioning: true
entryTypes:
  - 8039b83d-a753-40d8-a665-44b50602ab9a # Navigation Items
handle: navigationLinks
maxAuthors: 1
name: 'Navigation Links'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f6eaef1f-2f88-4856-8eee-c5ae9620f572: # Craft Template
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 7e683719-e427-4b5e-b2f4-4ccfc8a345c8
type: structure
